"""
Enterprise RAG AI Assistant — User ORM Model
=============================================
Defines the ``users`` table using SQLAlchemy 2.0 ``mapped_column`` syntax
with full type annotations.

Database compatibility:
  - PostgreSQL (production): Uses native UUID and native ENUM types.
  - SQLite (test suite):     Automatically maps to VARCHAR/CHAR and CHECK constraints.

Table: users
"""

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import Boolean, Enum, String, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TimestampMixin
from app.models.enums import UserRole

if TYPE_CHECKING:
    from app.models.document import Document


class User(TimestampMixin, Base):
    """
    ORM model representing a registered user.

    Columns
    -------
    id              UUID primary key, auto-generated by SQLAlchemy.
    full_name       Display name of the user.
    email           Unique email address (used as the login identifier).
    hashed_password bcrypt-hashed password string. Plain-text is NEVER stored.
    role            RBAC role enum: UserRole.USER or UserRole.ADMIN.
    is_active       False means the account is suspended (soft-disable).
    is_verified     True once the user has confirmed their email address.
    created_at      Managed by TimestampMixin.
    updated_at      Managed by TimestampMixin.
    """

    __tablename__ = "users"

    # ── Primary Key (SQLAlchemy 2.0 Uuid type for native PG UUID / SQLite CHAR fallback) ──
    id: Mapped[uuid.UUID] = mapped_column(
        Uuid,
        primary_key=True,
        default=uuid.uuid4,
        comment="Universally unique record identifier.",
    )

    # ── Identity ──────────────────────────────────────────────────────────────
    full_name: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="Full display name of the user.",
    )
    email: Mapped[str] = mapped_column(
        String(255),
        unique=True,
        nullable=False,
        index=True,
        comment="Unique email address used as the login identifier.",
    )
    hashed_password: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="bcrypt-hashed representation of the user's password.",
    )

    # ── RBAC (SQLAlchemy 2.0 Enum mapping) ───────────────────────────────────
    role: Mapped[UserRole] = mapped_column(
        Enum(UserRole, name="userrole", native_enum=True, create_constraint=True),
        nullable=False,
        default=UserRole.USER,
        server_default=UserRole.USER.value,
        comment="Role-based access control assignment: 'USER' or 'ADMIN'.",
    )

    # ── Account Status ────────────────────────────────────────────────────────
    is_active: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=True,
        server_default="1",
        comment="False indicates the account has been suspended.",
    )
    is_verified: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="0",
        comment="True once the user has verified their email address.",
    )

    # ── Relationships (Lazy Async Loading) ───────────────────────────────────
    documents: Mapped[list["Document"]] = relationship(
        "Document",
        back_populates="user",
        cascade="all, delete-orphan",
        lazy="raise",
    )

    # ── Computed helpers ──────────────────────────────────────────────────────
    @property
    def is_admin(self) -> bool:
        """Convenience property — True when the user holds the ADMIN role."""
        return self.role == UserRole.ADMIN

    def __repr__(self) -> str:
        return f"<User id={self.id!s} email={self.email!r} role={self.role.value!r}>"
