"""
Enterprise RAG AI Assistant — LLM Client Providers
=====================================================
Abstracts API requests to OpenAI, Google Gemini, and Local/Ollama.
"""

from __future__ import annotations

import abc
import json
from collections.abc import AsyncGenerator

import httpx

from app.config.settings import settings


class LLMProviderError(Exception):
    """Base exception for LLM provider execution failures."""

    pass


class LLMProvider(abc.ABC):
    """
    Abstract Base Class outlining interface contract for LLM provider clients.
    """

    @abc.abstractmethod
    async def generate_response(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.2,
        max_tokens: int = 1000,
    ) -> tuple[str, dict[str, int]]:
        """
        Send prompt parameters to LLM and returns text response + token usage accounting.

        Returns
        -------
        response_text      The generated raw text response.
        token_usage        Dictionary with prompt_tokens, completion_tokens, total_tokens.
        """
        pass

    @abc.abstractmethod
    async def generate_response_stream(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.2,
        max_tokens: int = 1000,
    ) -> AsyncGenerator[str, None]:
        """
        Yields text tokens incrementally as they are generated by the LLM.
        """
        yield ""


class GeminiProvider(LLMProvider):
    """
    Client for Google Gemini API via native REST requests.
    """

    def __init__(
        self, api_key: str | None = None, model: str = "gemini-1.5-flash"
    ) -> None:
        self.api_key = api_key or settings.gemini_api_key
        self.model = model

    async def generate_response(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.2,
        max_tokens: int = 1000,
    ) -> tuple[str, dict[str, int]]:
        if not self.api_key:
            raise LLMProviderError("Google Gemini API Key is not configured.")

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:generateContent?key={self.api_key}"
        payload = {
            "contents": [{"role": "user", "parts": [{"text": user_prompt}]}],
            "systemInstruction": {"parts": [{"text": system_prompt}]},
            "generationConfig": {
                "temperature": temperature,
                "maxOutputTokens": max_tokens,
            },
        }

        async with httpx.AsyncClient(timeout=60.0) as client:
            try:
                resp = await client.post(url, json=payload)
                if not resp.is_success:
                    raise LLMProviderError(
                        f"Gemini API returned error HTTP {resp.status_code}: {resp.text}"
                    )

                res_json = resp.json()

                # Check for errors in response body
                if "error" in res_json:
                    raise LLMProviderError(f"Gemini API Error: {res_json['error']}")

                candidates = res_json.get("candidates", [])
                if not candidates:
                    raise LLMProviderError(
                        "Gemini API returned empty candidates list (possibly blocked content)."
                    )

                text = (
                    candidates[0]
                    .get("content", {})
                    .get("parts", [{}])[0]
                    .get("text", "")
                )

                usage = res_json.get("usageMetadata", {})
                prompt_tokens = usage.get("promptTokenCount", 0)
                completion_tokens = usage.get("candidatesTokenCount", 0)
                total_tokens = usage.get("totalTokenCount", 0)

                token_usage = {
                    "prompt_tokens": prompt_tokens,
                    "completion_tokens": completion_tokens,
                    "total_tokens": total_tokens or (prompt_tokens + completion_tokens),
                }

                return text, token_usage

            except httpx.HTTPError as he:
                raise LLMProviderError(f"HTTP request to Gemini failed: {he!s}") from he
            except Exception as e:
                raise LLMProviderError(f"Failed to parse Gemini response: {e!s}") from e

    async def generate_response_stream(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.2,
        max_tokens: int = 1000,
    ) -> AsyncGenerator[str, None]:
        if not self.api_key:
            raise LLMProviderError("Google Gemini API Key is not configured.")

        url = f"https://generativelanguage.googleapis.com/v1beta/models/{self.model}:streamGenerateContent?key={self.api_key}"
        payload = {
            "contents": [{"role": "user", "parts": [{"text": user_prompt}]}],
            "systemInstruction": {"parts": [{"text": system_prompt}]},
            "generationConfig": {
                "temperature": temperature,
                "maxOutputTokens": max_tokens,
            },
        }

        async with httpx.AsyncClient(timeout=60.0) as client:
            try:
                async with client.stream("POST", url, json=payload) as response:
                    if not response.is_success:
                        raise LLMProviderError(
                            f"Gemini stream failed with HTTP {response.status_code}"
                        )

                    buffer = ""
                    async for chunk in response.aiter_text():
                        buffer += chunk
                        while True:
                            start = buffer.find("{")
                            if start == -1:
                                break

                            brace_count = 0
                            end = -1
                            for i in range(start, len(buffer)):
                                if buffer[i] == "{":
                                    brace_count += 1
                                elif buffer[i] == "}":
                                    brace_count -= 1
                                    if brace_count == 0:
                                        end = i
                                        break
                            if end == -1:
                                break

                            obj_str = buffer[start : end + 1]
                            buffer = buffer[end + 1 :]

                            try:
                                obj = json.loads(obj_str)
                                text = obj["candidates"][0]["content"]["parts"][0].get(
                                    "text", ""
                                )
                                if text:
                                    yield text
                            except Exception:
                                pass
            except httpx.HTTPError as he:
                raise LLMProviderError(
                    f"HTTP stream request to Gemini failed: {he!s}"
                ) from he
            except Exception as e:
                raise LLMProviderError(f"Failed to parse Gemini stream: {e!s}") from e


class OpenAIProvider(LLMProvider):
    """
    Client for OpenAI Chat Completions API via REST.
    """

    def __init__(self, api_key: str | None = None, model: str = "gpt-4o-mini") -> None:
        self.api_key = api_key or settings.openai_api_key
        self.model = model

    async def generate_response(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.2,
        max_tokens: int = 1000,
    ) -> tuple[str, dict[str, int]]:
        if not self.api_key:
            raise LLMProviderError("OpenAI API Key is not configured.")

        url = "https://api.openai.com/v1/chat/completions"
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": temperature,
            "max_tokens": max_tokens,
        }

        async with httpx.AsyncClient(timeout=60.0) as client:
            try:
                resp = await client.post(url, json=payload, headers=headers)
                if not resp.is_success:
                    raise LLMProviderError(
                        f"OpenAI API returned error HTTP {resp.status_code}: {resp.text}"
                    )

                res_json = resp.json()

                choices = res_json.get("choices", [])
                if not choices:
                    raise LLMProviderError("OpenAI API returned empty choices list.")

                text = choices[0].get("message", {}).get("content", "")

                usage = res_json.get("usage", {})
                prompt_tokens = usage.get("prompt_tokens", 0)
                completion_tokens = usage.get("completion_tokens", 0)
                total_tokens = usage.get("total_tokens", 0)

                token_usage = {
                    "prompt_tokens": prompt_tokens,
                    "completion_tokens": completion_tokens,
                    "total_tokens": total_tokens or (prompt_tokens + completion_tokens),
                }

                return text, token_usage

            except httpx.HTTPError as he:
                raise LLMProviderError(f"HTTP request to OpenAI failed: {he!s}") from he
            except Exception as e:
                raise LLMProviderError(f"Failed to parse OpenAI response: {e!s}") from e

    async def generate_response_stream(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.2,
        max_tokens: int = 1000,
    ) -> AsyncGenerator[str, None]:
        if not self.api_key:
            raise LLMProviderError("OpenAI API Key is not configured.")

        url = "https://api.openai.com/v1/chat/completions"
        headers = {
            "Authorization": f"Bearer {self.api_key}",
            "Content-Type": "application/json",
        }
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": temperature,
            "max_tokens": max_tokens,
            "stream": True,
        }

        async with httpx.AsyncClient(timeout=60.0) as client:
            try:
                async with client.stream(
                    "POST", url, json=payload, headers=headers
                ) as response:
                    if not response.is_success:
                        raise LLMProviderError(
                            f"OpenAI stream failed with HTTP {response.status_code}"
                        )

                    async for line in response.aiter_lines():
                        line = line.strip()
                        if not line:
                            continue
                        if line.startswith("data: "):
                            data_str = line[6:]
                            if data_str == "[DONE]":
                                break
                            try:
                                data = json.loads(data_str)
                                text = data["choices"][0]["delta"].get("content", "")
                                if text:
                                    yield text
                            except Exception:
                                pass
            except httpx.HTTPError as he:
                raise LLMProviderError(
                    f"HTTP stream request to OpenAI failed: {he!s}"
                ) from he
            except Exception as e:
                raise LLMProviderError(f"Failed to parse OpenAI stream: {e!s}") from e


class OllamaProvider(LLMProvider):
    """
    Client for Local/Ollama Chat API using OpenAI compatibility layers.
    """

    def __init__(
        self, base_url: str = "http://localhost:11434/v1", model: str = "llama3"
    ) -> None:
        self.base_url = base_url
        self.model = model

    async def generate_response(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.2,
        max_tokens: int = 1000,
    ) -> tuple[str, dict[str, int]]:
        url = f"{self.base_url}/chat/completions"
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": temperature,
            "max_tokens": max_tokens,
        }

        async with httpx.AsyncClient(timeout=60.0) as client:
            try:
                resp = await client.post(url, json=payload)
                if not resp.is_success:
                    raise LLMProviderError(
                        f"Ollama returned error HTTP {resp.status_code}: {resp.text}"
                    )

                res_json = resp.json()
                choices = res_json.get("choices", [])
                if not choices:
                    raise LLMProviderError("Ollama returned empty choices list.")

                text = choices[0].get("message", {}).get("content", "")

                usage = res_json.get("usage", {})
                prompt_tokens = usage.get("prompt_tokens", 0)
                completion_tokens = usage.get("completion_tokens", 0)
                total_tokens = usage.get("total_tokens", 0)

                # Fallback estimation if Ollama doesn't return usage metadata
                if not prompt_tokens and not completion_tokens:
                    prompt_tokens = len(system_prompt.split()) + len(
                        user_prompt.split()
                    )
                    completion_tokens = len(text.split())
                    total_tokens = prompt_tokens + completion_tokens

                token_usage = {
                    "prompt_tokens": prompt_tokens,
                    "completion_tokens": completion_tokens,
                    "total_tokens": total_tokens,
                }

                return text, token_usage

            except httpx.HTTPError as he:
                raise LLMProviderError(f"HTTP request to Ollama failed: {he!s}") from he
            except Exception as e:
                raise LLMProviderError(f"Failed to parse Ollama response: {e!s}") from e

    async def generate_response_stream(
        self,
        system_prompt: str,
        user_prompt: str,
        temperature: float = 0.2,
        max_tokens: int = 1000,
    ) -> AsyncGenerator[str, None]:
        url = f"{self.base_url}/chat/completions"
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": user_prompt},
            ],
            "temperature": temperature,
            "max_tokens": max_tokens,
            "stream": True,
        }

        async with httpx.AsyncClient(timeout=60.0) as client:
            try:
                async with client.stream("POST", url, json=payload) as response:
                    if not response.is_success:
                        raise LLMProviderError(
                            f"Ollama stream failed with HTTP {response.status_code}"
                        )

                    async for line in response.aiter_lines():
                        line = line.strip()
                        if not line:
                            continue
                        if line.startswith("data: "):
                            data_str = line[6:]
                            if data_str == "[DONE]":
                                break
                            try:
                                data = json.loads(data_str)
                                text = data["choices"][0]["delta"].get("content", "")
                                if text:
                                    yield text
                            except Exception:
                                pass
            except httpx.HTTPError as he:
                raise LLMProviderError(
                    f"HTTP stream request to Ollama failed: {he!s}"
                ) from he
            except Exception as e:
                raise LLMProviderError(f"Failed to parse Ollama stream: {e!s}") from e


def get_llm_provider(
    provider_name: str | None = None,
    api_key: str | None = None,
    model: str | None = None,
) -> LLMProvider:
    """
    Factory function returning the active LLMProvider instance.
    """
    p_name = (provider_name or settings.llm_provider).lower()

    if p_name == "gemini":
        return GeminiProvider(api_key=api_key, model=model or "gemini-1.5-flash")
    elif p_name == "openai":
        return OpenAIProvider(api_key=api_key, model=model or "gpt-4o-mini")
    elif p_name == "ollama":
        return OllamaProvider(model=model or "llama3")
    else:
        raise ValueError(f"Unsupported LLM provider: {provider_name}")
