"""
Enterprise RAG AI Assistant — SQLAlchemy Declarative Base & Mixins
==================================================================
All ORM models must inherit from ``Base`` defined here.
Two reusable mixins are provided so every table gets consistent
primary-key and timestamp columns without copy-pasting.

Design notes:
  - Uses SQLAlchemy 2.0 ``DeclarativeBase`` (not the legacy ``declarative_base()``).
  - UUID primary keys are generated server-side via PostgreSQL's ``gen_random_uuid()``.
    A Python fallback using ``uuid.uuid4`` is provided for SQLite tests.
  - Timestamps use ``func.now()`` so the database clock is authoritative.
"""

import uuid
from datetime import datetime

from sqlalchemy import DateTime, func, text
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column

# =============================================================================
# Declarative Base
# =============================================================================


class Base(DeclarativeBase):
    """
    Base class for all SQLAlchemy ORM models.

    Every model in ``app/models/`` must inherit from this class so that
    Alembic's ``autogenerate`` can discover them and create migrations.
    """

    pass


# =============================================================================
# Mixins
# =============================================================================


class UUIDPrimaryKeyMixin:
    """
    Mixin that adds a UUID primary key column named ``id``.

    The default is generated by Python (``uuid.uuid4``) so it works with
    both PostgreSQL and SQLite (used in the test suite).
    """

    id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
        server_default=text("gen_random_uuid()"),
        comment="Universally unique record identifier.",
    )


class TimestampMixin:
    """
    Mixin that adds ``created_at`` and ``updated_at`` audit columns.

    Both columns are set by the database clock:
      - ``created_at`` is set once on INSERT.
      - ``updated_at`` is updated on every UPDATE via ``onupdate``.
    """

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
        comment="UTC timestamp when this record was first created.",
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
        comment="UTC timestamp of the most recent update to this record.",
    )
