"""Initial user migration

Revision ID: b9f0be8d2f5b
Revises:
Create Date: 2026-07-17 09:19:42.934928
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'b9f0be8d2f5b'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Universally unique record identifier.'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Full display name of the user.'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Unique email address used as the login identifier.'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment="bcrypt-hashed representation of the user's password."),
    sa.Column('role', sa.Enum('user', 'admin', name='userrole', create_constraint=True), server_default='user', nullable=False, comment="Role-based access control assignment: 'user' or 'admin'."),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False, comment='False indicates the account has been suspended.'),
    sa.Column('is_verified', sa.Boolean(), server_default='0', nullable=False, comment='True once the user has verified their email address.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when this record was first created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update to this record.'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
