"""add_chunks_table

Revision ID: 224c26d47e35
Revises: 5abcd6aa2a3c
Create Date: 2026-07-18 08:15:54.825040
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '224c26d47e35'
down_revision: str | None = '5abcd6aa2a3c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunks',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Universally unique identifier for this chunk.'),
    sa.Column('document_id', sa.Uuid(), nullable=False, comment='The source document this chunk belongs to.'),
    sa.Column('chunk_index', sa.Integer(), nullable=False, comment='The sequence index of this chunk in the document.'),
    sa.Column('text', sa.Text(), nullable=False, comment='The semantic text content of this chunk.'),
    sa.Column('token_count', sa.Integer(), nullable=False, comment='Number of tokens in the text.'),
    sa.Column('character_count', sa.Integer(), nullable=False, comment='Length of clean chunk text.'),
    sa.Column('word_count', sa.Integer(), nullable=False, comment='Whitespace-delimited word count.'),
    sa.Column('reading_time_estimate', sa.Float(), nullable=False, comment='Estimated reading time in seconds.'),
    sa.Column('page_number', sa.Integer(), nullable=False, comment='Page number of the source document where this chunk starts.'),
    sa.Column('section_title', sa.String(length=255), nullable=True, comment='Heading or section name this chunk belongs to.'),
    sa.Column('heading_level', sa.Integer(), nullable=True, comment='Heading level (e.g. 1 for H1, 2 for H2) if chunk is heading-bounded.'),
    sa.Column('language', sa.String(length=10), nullable=False, comment='ISO 639-1 language code.'),
    sa.Column('metadata', sa.JSON(), nullable=True, comment='Enriched key-value metadata.'),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False, comment='SHA-256 hash of the chunk text to prevent duplicates.'),
    sa.Column('version', sa.String(length=20), nullable=False, comment='Chunking pipeline schema version.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when this record was first created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update to this record.'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chunks_chunk_index'), 'chunks', ['chunk_index'], unique=False)
    op.create_index(op.f('ix_chunks_document_id'), 'chunks', ['document_id'], unique=False)
    op.create_index(op.f('ix_chunks_sha256_hash'), 'chunks', ['sha256_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chunks_sha256_hash'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_document_id'), table_name='chunks')
    op.drop_index(op.f('ix_chunks_chunk_index'), table_name='chunks')
    op.drop_table('chunks')
    # ### end Alembic commands ###
