"""create_agent_tables

Revision ID: a77b9a151b5c
Revises: b308be7e5f1b
Create Date: 2026-07-19 07:07:00.782045
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a77b9a151b5c'
down_revision: str | None = 'b308be7e5f1b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique run identifier.'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Requesting user.'),
    sa.Column('session_id', sa.Uuid(), nullable=True, comment='Associated chat session (optional).'),
    sa.Column('question', sa.Text(), nullable=False, comment='Original user question.'),
    sa.Column('final_answer', sa.Text(), nullable=True, comment='LLM-generated final answer.'),
    sa.Column('tools_called', sa.JSON(), nullable=True, comment='Ordered list of tool IDs that were invoked.'),
    sa.Column('total_tool_calls', sa.Integer(), nullable=False, comment='Total number of tool invocations in this run.'),
    sa.Column('total_latency_ms', sa.Integer(), nullable=False, comment='Wall-clock time for the entire run in milliseconds.'),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False, comment='Prompt tokens consumed.'),
    sa.Column('completion_tokens', sa.Integer(), nullable=False, comment='Completion tokens generated.'),
    sa.Column('provider', sa.String(length=50), nullable=True, comment='LLM provider used (gemini, openai, ollama).'),
    sa.Column('model_name', sa.String(length=100), nullable=True, comment='Specific model name.'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='Whether the run completed successfully.'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error detail if success=False.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when the run was initiated.'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_runs_session_id'), 'agent_runs', ['session_id'], unique=False)
    op.create_index(op.f('ix_agent_runs_user_id'), 'agent_runs', ['user_id'], unique=False)
    op.create_table('agent_tool_calls',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique tool call identifier.'),
    sa.Column('run_id', sa.Uuid(), nullable=False, comment='Parent AgentRun.'),
    sa.Column('tool_id', sa.String(length=100), nullable=False, comment="Registered tool identifier (e.g. 'semantic_search')."),
    sa.Column('tool_name', sa.String(length=200), nullable=False, comment='Human-readable tool name.'),
    sa.Column('parameters', sa.JSON(), nullable=True, comment='Parameters passed to the tool.'),
    sa.Column('result', sa.JSON(), nullable=True, comment='Serialized ToolResult (truncated if large).'),
    sa.Column('latency_ms', sa.Integer(), nullable=False, comment='Tool execution wall-clock time in milliseconds.'),
    sa.Column('retries', sa.Integer(), nullable=False, comment='Number of retry attempts before success or final failure.'),
    sa.Column('success', sa.Boolean(), nullable=False, comment='Whether this tool call succeeded.'),
    sa.Column('error', sa.Text(), nullable=True, comment='Error message if success=False.'),
    sa.Column('called_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='UTC timestamp when the tool was invoked.'),
    sa.ForeignKeyConstraint(['run_id'], ['agent_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tool_calls_run_id'), 'agent_tool_calls', ['run_id'], unique=False)
    op.alter_column('documents', 'processing_status',
               existing_type=sa.VARCHAR(length=20),
               comment="Document state: 'UPLOADED','QUEUED','PROCESSING','PROCESSED','FAILED'.",
               existing_comment="Document state: 'uploaded', 'processing', 'completed', 'failed'.",
               existing_nullable=False,
               existing_server_default=sa.text("'UPLOADED'::character varying"))
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', name='userrole'),
               comment="Role-based access control assignment: 'USER' or 'ADMIN'.",
               existing_comment="Role-based access control assignment: 'user' or 'admin'.",
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::userrole"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('USER', 'ADMIN', name='userrole'),
               comment="Role-based access control assignment: 'user' or 'admin'.",
               existing_comment="Role-based access control assignment: 'USER' or 'ADMIN'.",
               existing_nullable=False,
               existing_server_default=sa.text("'USER'::userrole"))
    op.alter_column('documents', 'processing_status',
               existing_type=sa.VARCHAR(length=20),
               comment="Document state: 'uploaded', 'processing', 'completed', 'failed'.",
               existing_comment="Document state: 'UPLOADED','QUEUED','PROCESSING','PROCESSED','FAILED'.",
               existing_nullable=False,
               existing_server_default=sa.text("'UPLOADED'::character varying"))
    op.drop_index(op.f('ix_agent_tool_calls_run_id'), table_name='agent_tool_calls')
    op.drop_table('agent_tool_calls')
    op.drop_index(op.f('ix_agent_runs_user_id'), table_name='agent_runs')
    op.drop_index(op.f('ix_agent_runs_session_id'), table_name='agent_runs')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
