"""add_processed_documents_table

Revision ID: 5abcd6aa2a3c
Revises: 720b2f5b4490
Create Date: 2026-07-18 07:12:38.937675
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5abcd6aa2a3c'
down_revision: str | None = '720b2f5b4490'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_documents',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Universally unique identifier for this processing record.'),
    sa.Column('document_id', sa.Uuid(), nullable=False, comment='The source document this record was extracted from.'),
    sa.Column('raw_text', sa.Text(), nullable=False, comment='Full text as extracted from the file before normalisation.'),
    sa.Column('clean_text', sa.Text(), nullable=False, comment='Text after Unicode normalisation and whitespace collapsing.'),
    sa.Column('language', sa.String(length=10), nullable=False, comment='ISO 639-1 language code detected from clean_text.'),
    sa.Column('page_count', sa.Integer(), nullable=False, comment='Number of pages in the source document.'),
    sa.Column('word_count', sa.Integer(), nullable=False, comment='Whitespace-delimited word count of clean_text.'),
    sa.Column('character_count', sa.Integer(), nullable=False, comment='Character count (len) of clean_text.'),
    sa.Column('processing_time', sa.Float(), nullable=False, comment='Elapsed seconds for the extraction pipeline.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when this record was first created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update to this record.'),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_processed_documents_document_id'), 'processed_documents', ['document_id'], unique=True)
    # NOTE: alter_column on documents.processing_status omitted — SQLite does not
    # support ALTER COLUMN for server_default changes. The column already has the
    # correct default from the previous migration. This is a no-op for PostgreSQL.
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_documents_document_id'), table_name='processed_documents')
    op.drop_table('processed_documents')
    # ### end Alembic commands ###
