"""add chat tables

Revision ID: 433ba6730bf1
Revises: 6bcda2f24301
Create Date: 2026-07-18 10:09:05.047465
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '433ba6730bf1'
down_revision: str | None = '6bcda2f24301'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_sessions',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the chat session.'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='User who owns this conversation session.'),
    sa.Column('title', sa.String(length=255), nullable=False, comment='The display title of this chat session.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when this record was first created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update to this record.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_messages',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Unique identifier for the chat message.'),
    sa.Column('session_id', sa.Uuid(), nullable=False, comment='The chat session this message belongs to.'),
    sa.Column('role', sa.String(length=20), nullable=False, comment='The role of the sender: user, assistant, system.'),
    sa.Column('content', sa.Text(), nullable=False, comment='The text content of the message.'),
    sa.Column('citations', sa.JSON(), nullable=True, comment='Grounded sources metadata citation matching list.'),
    sa.Column('tokens', sa.JSON(), nullable=True, comment='Token billing stats (prompt, completion, total).'),
    sa.Column('latency', sa.JSON(), nullable=True, comment='Detailed execution latencies in milliseconds.'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when the message was sent.'),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # op.alter_column('chunks', 'embedding',
    #            existing_type=sa.NUMERIC(precision=768),
    #            type_=pgvector.sqlalchemy.vector.VECTOR(dim=768),
    #            existing_nullable=True)
    # op.create_index('ix_chunks_embedding', 'chunks', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.alter_column('documents', 'processing_status',
               existing_type=sa.VARCHAR(length=20),
               server_default='UPLOADED',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'processing_status',
               existing_type=sa.VARCHAR(length=20),
               server_default=sa.text("'uploaded'"),
               existing_nullable=False)
    # op.drop_index('ix_chunks_embedding', table_name='chunks', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # op.alter_column('chunks', 'embedding',
    #            existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=768),
    #            type_=sa.NUMERIC(precision=768),
    #            existing_nullable=True)
    op.drop_table('chat_messages')
    op.drop_table('chat_sessions')
    # ### end Alembic commands ###
