"""Add documents table

Revision ID: 720b2f5b4490
Revises: b9f0be8d2f5b
Create Date: 2026-07-17 09:37:03.127486
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '720b2f5b4490'
down_revision: str | None = 'b9f0be8d2f5b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documents',
    sa.Column('id', sa.Uuid(), nullable=False, comment='Universally unique identifier for this document.'),
    sa.Column('user_id', sa.Uuid(), nullable=False, comment='Owner of this document.'),
    sa.Column('original_filename', sa.String(length=255), nullable=False, comment='Original name of the file upon upload.'),
    sa.Column('stored_filename', sa.String(length=255), nullable=False, comment='Obfuscated filename stored physically on disk.'),
    sa.Column('mime_type', sa.String(length=100), nullable=False, comment='Content MIME type of the document.'),
    sa.Column('file_size', sa.BigInteger(), nullable=False, comment='Size of the document in bytes.'),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False, comment='SHA-256 integrity checksum for duplicate detection.'),
    sa.Column('storage_path', sa.String(length=500), nullable=False, comment='Physical location of the file on the local storage partition.'),
    sa.Column('processing_status', sa.String(length=20), server_default='uploaded', nullable=False, comment="Document state: 'uploaded', 'processing', 'completed', 'failed'."),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp when this record was first created.'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='UTC timestamp of the most recent update to this record.'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    op.create_index(op.f('ix_documents_sha256_hash'), 'documents', ['sha256_hash'], unique=False)
    op.create_index(op.f('ix_documents_user_id'), 'documents', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_user_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_sha256_hash'), table_name='documents')
    op.drop_table('documents')
    # ### end Alembic commands ###
